apiVersion: v1
kind: Service
metadata:
  name: econ-worker-service
spec:
  selector:
    app: econ-worker
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
  loadBalancerIP: 192.168.0.161


