apiVersion: v1
kind: Service
metadata:
  name: docusaurus-service
  namespace: default
spec:
  selector:
    app: docusaurus
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 8080
  type: LoadBalancer
  loadBalancerIP: 192.168.0.159
