apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: omada-data-pvc
  namespace: omada
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: omada-logs-pvc
  namespace: omada
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

