apiVersion: v1
kind: Service
metadata:
  name: omada-service
  namespace: omada
spec:
  selector:
    app: omada-controller
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 8088
      targetPort: 8088
    - name: https
      protocol: TCP
      port: 8043
      targetPort: 8043
    - name: portal
      protocol: TCP
      port: 8843
      targetPort: 8843
    - name: app-discovery
      protocol: TCP
      port: 27001
      targetPort: 27001
    - name: adopt-v1
      protocol: TCP
      port: 29812
      targetPort: 29812
    - name: upgrade-v1
      protocol: TCP
      port: 29813
      targetPort: 29813
    - name: manager-v1
      protocol: TCP
      port: 29811
      targetPort: 29811
    - name: manager-v2
      protocol: TCP
      port: 29814
      targetPort: 29814
    - name: discovery
      protocol: TCP
      port: 29810
      targetPort: 29810
    - name: transfer-v2
      protocol: TCP
      port: 29815
      targetPort: 29815
    - name: rtty
      protocol: TCP
      port: 29816
      targetPort: 29816

