apiVersion: v1
kind: Service
metadata:
  name: ecociel-service
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.0.162
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: ecociel

