apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-wasm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-wasm
  template:
    metadata:
      labels:
        app: hello-wasm
    spec:
      containers:
      - name: hello-wasm
        image: inquisitor1337/hello-wasm:2
        command: ["/usr/local/bin/wasmtime", "/app/hello.wasm"]

