apiVersion: v1
kind: Pod
metadata:
  name: hello-wasm
spec:
  containers:
    - name: hello-wasm
      image: inquisitor1337/hello-wasm:3
      command: ["/usr/local/bin/wasmtime", "/app/hello.wasm"]
      env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: POD_MAC
          value: "02:42:ac:11:00:02" 
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace

