apiVersion: batch/v1
kind: CronJob
metadata:
  name: iperf3-cronjob
  namespace: iperf3
spec:
  schedule: "0 * * * *" # Run every hour
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: iperf3
            image: inquisitor1337/iperf4:latest
            args: ["-s"] 
            ports:
            - containerPort: 5201
          restartPolicy: OnFailure

