apiVersion: apps/v1
kind: Deployment
metadata:
  name: iperf3-deployment
  namespace: iperf3  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iperf3
  template:
    metadata:
      labels:
        app: iperf3
    spec:
      containers:
      - name: iperf3
        image: inquisitor1337/iperf3:latest
        ports:
        - containerPort: 5201

