apiVersion: v1
kind: Service
metadata:
  name: iperf3-service
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.0.160
  ports:
  - port: 5201
    targetPort: 5201
    protocol: TCP
    name: tcp
  - port: 5201
    targetPort: 5201
    protocol: UDP
    name: udp
  selector:
    app: iperf3

