metadata:
  name: hemidall-info
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hemidall-info
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hemidall-info
  template:
    metadata:
      name: hemidall-info
      labels:
        app: hemidall-info
    spec:
      containers:
        - name: hemidall-info
          image: inquisitor1337/hemidall-stackit1
          ports:
            - containerPort: 8080
              name: http
          env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: POD_SERVICE_ACCOUNT
            valueFrom:
              fieldRef:
                fieldPath: spec.serviceAccountName
      serviceAccountName: hemidall-stackit-sa
