---
apiVersion: v1
kind: services
metadata:
  name: hemidall-info
spec:
  selector:
    app: hemidall-info
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  loadBalancerIP: 192.168.0.177
